Hello everyone, I am sqrt676 (Sumit Pandey ) trying here to implement KNN algo on diabetes data set.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
df.describe

<bound method NDFrame.describe of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Outcome
0                       0.627   50        1
1                       0.351   31        0
2                       0.672   32        1
3                       0.167   21        0
4                       2.288   33        1
..                        ...  ...      ...
763                     0.171   63        0
764                     0.340   27        0
765                     0.245   30        0
766                     0.349   47        1
767                     0.315   23        0

[768 rows x 9 columns]>

In [4]:
df.shape

(768, 9)

In [11]:
df_prob_rows=df[(df['BloodPressure']==0) | (df['SkinThickness']==0 )| (df['BMI']==0)]

In [14]:
df_prob_rows.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
2,8,183,64,0,0,23.3,0.672,32,1
5,5,116,74,0,0,25.6,0.201,30,0
7,10,115,0,0,0,35.3,0.134,29,0
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0

In [ ]:
df_prob_rows.describe
#this gives output of errorness rows

In [16]:
df_prob_rows.shape
#this gives shape of errorness rows set

(231, 9)

In [17]:
df_reject = df[(df['BloodPressure']!=0) & (df['SkinThickness']!=0) & (df['BMI']!=0)]
df_replace = df
columns = ['BloodPressure', 'SkinThickness', 'BMI']
for col in columns:
    val = df[col].mean()
    df_replace[col] = df[col].replace(0, val)
df_reject.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1

In [18]:
df_reject.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1

In [19]:
df_replace.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.000000,35.000000,0,33.600000,0.627,50,1
1,1,85,66.000000,29.000000,0,26.600000,0.351,31,0
2,8,183,64.000000,20.536458,0,23.300000,0.672,32,1
3,1,89,66.000000,23.000000,94,28.100000,0.167,21,0
4,0,137,40.000000,35.000000,168,43.100000,2.288,33,1
5,5,116,74.000000,20.536458,0,25.600000,0.201,30,0
6,3,78,50.000000,32.000000,88,31.000000,0.248,26,1
7,10,115,69.105469,20.536458,0,35.300000,0.134,29,0
8,2,197,70.000000,45.000000,543,30.500000,0.158,53,1
9,8,125,96.000000,20.536458,0,31.992578,0.232,54,1

*Normalising the data*

In [20]:
from sklearn import preprocessing

In [21]:
x=df.values
min_max_scaler=preprocessing.MinMaxScaler()
x_scaled= min_max_scaler.fit_transform(x)
df_n1=pd.DataFrame(x_scaled)
df_n1.head()

,0,1,2,3,4,5,6,7,8
0,0.352941,0.743719,0.489796,0.304348,0.000000,0.314928,0.234415,0.483333,1.0
1,0.058824,0.427136,0.428571,0.239130,0.000000,0.171779,0.116567,0.166667,0.0
2,0.470588,0.919598,0.408163,0.147135,0.000000,0.104294,0.253629,0.183333,1.0
3,0.058824,0.447236,0.428571,0.173913,0.111111,0.202454,0.038002,0.000000,0.0
4,0.000000,0.688442,0.163265,0.304348,0.198582,0.509202,0.943638,0.200000,1.0

In [22]:
df_replace_n=(df_replace-df_replace.min())/(df_replace.max()-df_replace.min())
df_replace_n.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.352941,0.743719,0.489796,0.304348,0.000000,0.314928,0.234415,0.483333,1.0
1,0.058824,0.427136,0.428571,0.239130,0.000000,0.171779,0.116567,0.166667,0.0
2,0.470588,0.919598,0.408163,0.147135,0.000000,0.104294,0.253629,0.183333,1.0
3,0.058824,0.447236,0.428571,0.173913,0.111111,0.202454,0.038002,0.000000,0.0
4,0.000000,0.688442,0.163265,0.304348,0.198582,0.509202,0.943638,0.200000,1.0

In [23]:
df_reject_n=(df_reject-df_reject.min())/(df_reject.max()-df_reject.min())
df_reject_n.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.352941,0.743719,0.558140,0.304348,0.000000,0.314928,0.232120,0.483333,1.0
1,0.058824,0.427136,0.488372,0.239130,0.000000,0.171779,0.113919,0.166667,0.0
3,0.058824,0.447236,0.488372,0.173913,0.111111,0.202454,0.035118,0.000000,0.0
4,0.000000,0.688442,0.186047,0.304348,0.198582,0.509202,0.943469,0.200000,1.0
6,0.176471,0.391960,0.302326,0.271739,0.104019,0.261759,0.069807,0.083333,1.0

In [24]:
df_mn=(df-df.mean())/df.std()
df_mn.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.639530,0.847771,-0.021031,0.871489,-0.692439,0.167147,0.468187,1.425067,1.365006
1,-0.844335,-1.122665,-0.516246,0.248516,-0.692439,-0.850980,-0.364823,-0.190548,-0.731643
2,1.233077,1.942458,-0.681318,-0.630243,-0.692439,-1.330954,0.604004,-0.105515,1.365006
3,-0.844335,-0.997558,-0.516246,-0.374456,0.123221,-0.632810,-0.920163,-1.040871,-0.731643
4,-1.141108,0.503727,-2.662181,0.871489,0.765337,1.548890,5.481337,-0.020483,1.365006

In [25]:
X_replace_n = df_replace_n.drop("Outcome",axis = 1)
y_replace_n = df_replace_n.Outcome
X_reject_n = df_reject_n.drop("Outcome",axis = 1)
y_reject_n = df_reject_n.Outcome

In [26]:
from sklearn.model_selection import train_test_split
X_train_replace,X_test_replace,y_train_replace,y_test_replace = train_test_split(X_replace_n,y_replace_n,test_size=0.3,random_state=42, stratify=y_replace_n)
from sklearn.model_selection import train_test_split
X_train_reject,X_test_reject,y_train_reject,y_test_reject = train_test_split(X_reject_n,y_reject_n,test_size=0.3,random_state=42, stratify=y_reject_n)

In [29]:
from sklearn.neighbors import KNeighborsClassifier

test_scores = []

for i in range(1,10):

    knn = KNeighborsClassifier(i)
    knn.fit(X_train_replace,y_train_replace)
    
    test_scores.append(knn.score(X_test_replace,y_test_replace))
print(test_scores)

[0.7402597402597403, 0.70995670995671, 0.7186147186147186, 0.70995670995671, 0.70995670995671, 0.7229437229437229, 0.7402597402597403, 0.7359307359307359, 0.7402597402597403]